"use client";

import { useState } from "react";
import Link from "next/link";
import { menuCatalog } from "@/data/menuData";
import { StudentModel } from "@/models/StudentModel";
import { PreOrderModel } from "@/models/PreOrderModel";

export default function ComplexBindingPage() {
  const [selectedItemId, setSelectedItemId] = useState<number>(menuCatalog[0].id);
  const [summary, setSummary] = useState<string | null>(null);
  const [validationError, setValidationError] = useState<string | null>(null);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setValidationError(null);

    const fd = new FormData(e.currentTarget);

    // Read nested dot-notation fields exactly as generated by ASP.NET's Html.TextBoxFor
    const studentNo = Number(fd.get("Student.StudentNo"));
    const studentName = String(fd.get("Student.StudentName") ?? "");
    const program = String(fd.get("Student.Program") ?? "");
    const quantity = Number(fd.get("Quantity"));

    // Validation checks
    if (!studentNo || studentNo <= 0) {
      setValidationError("Student number is required and must be valid.");
      return;
    }
    if (!studentName.trim()) {
      setValidationError("Student name is required.");
      return;
    }
    if (isNaN(quantity) || quantity < 1 || quantity > 20) {
      setValidationError("Quantity must be between 1 and 20.");
      return;
    }

    // Resolve selected MenuItem
    const selectedItem = menuCatalog.find((m) => m.id === selectedItemId) ?? null;

    // Instantiate nested complex model
    const student = new StudentModel(studentNo, studentName, program);
    const order = new PreOrderModel(quantity, student, selectedItem);

    // Safe null checks before using
    if (!order.student || !order.item) {
      setValidationError("Order incomplete: missing student or selected item.");
      return;
    }

    // Business logic handled by model method, not computed in view
    const total = order.getTotal();

    // Required format: Pre-order for Juan Dela Cruz (BSIT): 2 × Chicken Adobo = ₱130.00
    setSummary(
      `Pre-order for ${order.student.studentName} (${order.student.program}): ${order.quantity} × ${order.item.name} = ₱${total.toFixed(2)}`
    );
  }

  return (
    <div className="max-w-xl mx-auto p-6 font-sans">
      <Link href="/binding" className="text-sm text-orange-400 hover:underline mb-4 inline-block">
        ← Back to Binding Hub
      </Link>
      <h2 className="text-2xl font-bold mb-2 text-white">Task B4: Complex Binding</h2>
      <p className="text-sm text-slate-400 mb-6">
        Demonstrates nested model aggregation (<code className="text-orange-300">PreOrderModel</code> containing <code className="text-orange-300">StudentModel</code> &amp; <code className="text-orange-300">MenuItem</code>) using dot notation.
      </p>

      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Student nested section */}
        <fieldset className="border border-white/10 p-4 rounded-xl bg-white/5">
          <legend className="font-semibold text-xs tracking-wider uppercase px-2 text-orange-400">Student Details (Student.*)</legend>
          <div className="space-y-3 mt-2">
            <div>
              <label className="block text-xs font-semibold text-slate-300">Student No (Student.StudentNo)</label>
              <input
                name="Student.StudentNo"
                type="number"
                placeholder="20241001"
                required
                className="w-full border border-white/10 p-2.5 rounded-lg text-sm bg-black/40 text-white mt-1 focus:ring-2 focus:ring-orange-500 focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-300">Student Name (Student.StudentName)</label>
              <input
                name="Student.StudentName"
                placeholder="Juan Dela Cruz"
                required
                className="w-full border border-white/10 p-2.5 rounded-lg text-sm bg-black/40 text-white mt-1 focus:ring-2 focus:ring-orange-500 focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-300">Program (Student.Program)</label>
              <input
                name="Student.Program"
                placeholder="e.g. BSIT"
                required
                className="w-full border border-white/10 p-2.5 rounded-lg text-sm bg-black/40 text-white mt-1 focus:ring-2 focus:ring-orange-500 focus:outline-none"
              />
            </div>
          </div>
        </fieldset>

        {/* Menu item selection */}
        <fieldset className="border border-white/10 p-4 rounded-xl bg-white/5">
          <legend className="font-semibold text-xs tracking-wider uppercase px-2 text-orange-400">Menu Item Selection (Item.*)</legend>
          <div className="mt-2">
            <label className="block text-xs font-semibold text-slate-300">Select Item</label>
            <select
              name="Item.Id"
              value={selectedItemId}
              onChange={(e) => setSelectedItemId(Number(e.target.value))}
              className="w-full border border-white/10 p-2.5 rounded-lg text-sm bg-black/60 text-white mt-1 focus:ring-2 focus:ring-orange-500 focus:outline-none"
            >
              {menuCatalog.map((item) => (
                <option key={item.id} value={item.id} disabled={!item.isAvailable} className="bg-slate-900 text-white">
                  {item.name} ({item.category}) - ₱{item.price.toFixed(2)} {item.isAvailable ? "" : "[Sold out]"}
                </option>
              ))}
            </select>
          </div>
        </fieldset>

        <div>
          <label className="block text-sm font-semibold text-slate-300">Quantity (1 – 20)</label>
          <input
            name="Quantity"
            type="number"
            defaultValue={1}
            min={1}
            max={20}
            required
            className="w-full border border-white/10 p-2.5 rounded-lg text-sm bg-black/40 text-white mt-1 focus:ring-2 focus:ring-orange-500 focus:outline-none"
          />
        </div>

        <button
          type="submit"
          className="w-full bg-[#f26522] hover:bg-[#ea580c] text-white font-semibold py-3 rounded-lg transition shadow-lg shadow-orange-500/20"
        >
          Submit Pre-Order
        </button>
      </form>

      {validationError && (
        <div className="mt-4 p-3 bg-red-950/50 border border-red-500/50 text-red-300 rounded-lg text-sm">
          {validationError}
        </div>
      )}

      {summary && (
        <div className="mt-6 p-4 bg-emerald-950/40 border border-emerald-500/40 rounded-xl">
          <div className="text-xs uppercase font-semibold text-emerald-400 mb-1">Encapsulated Calculation Output:</div>
          <h4 className="text-emerald-200 font-bold text-base">{summary}</h4>
        </div>
      )}
    </div>
  );
}
